export interface Product {
  id: string;
  title: string;
  price: string;
  originalPrice: string;
  discount: string;
  image: string;
  badge?: string;
  badgeColor?: string;
  stock: string;
  rating: number;
  ratingCount: number;
  available: number;
  weight?: string;
}

export const featuredProducts: Product[] = [
  {
    id: '1',
    title: 'USDA Choice Angus Beef Stew Meat',
    price: '$49.99',
    originalPrice: '$79.99',
    discount: '38%',
    image: 'https://images.pexels.com/photos/5632599/pexels-photo-5632599.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 28,
  },
  {
    id: '2',
    title: 'Signature Wood-Fired Mushroom and Caramelized...',
    price: '$5.99',
    originalPrice: '$7.99',
    discount: '26%',
    image: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 45,
  },
  {
    id: '3',
    title: 'Perdue Simply Smart Organics Gluten free...',
    price: '$7.99',
    originalPrice: '$8.99',
    discount: '12%',
    image: 'https://images.pexels.com/photos/3621381/pexels-photo-3621381.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 60,
  },
  {
    id: '4',
    title: 'Organic Frozen Triple Berry Blend',
    price: '$15.79',
    originalPrice: '$17.99',
    discount: '12%',
    image: 'https://images.pexels.com/photos/5737452/pexels-photo-5737452.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 52,
    weight: '500g',
  },
  {
    id: '5',
    title: 'Organic 100% Grassfed 85_15 Ground Beef',
    price: '$5.99',
    originalPrice: '$6.99',
    discount: '14%',
    image: 'https://images.pexels.com/photos/2675968/pexels-photo-2675968.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 38,
  },
];

export const bestsellerProducts: Product[] = [
  {
    id: '11',
    title: 'Premium Fresh Salmon Fillet',
    price: '$12.99',
    originalPrice: '$17.99',
    discount: '28%',
    image: 'https://images.pexels.com/photos/4148989/pexels-photo-4148989.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 2,
    available: 42,
  },
  {
    id: '12',
    title: 'Organic Valley Grass Milk',
    price: '$3.49',
    originalPrice: '$4.99',
    discount: '30%',
    image: 'https://images.pexels.com/photos/5408/food-milk-glass-bottle.jpg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 3,
    available: 120,
    weight: '1L',
  },
  {
    id: '13',
    title: 'Fresh Garden Vegetables Mix',
    price: '$4.99',
    originalPrice: '$6.99',
    discount: '29%',
    image: 'https://images.pexels.com/photos/5632598/pexels-photo-5632598.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 75,
  },
  {
    id: '14',
    title: 'Greek Yogurt Plain',
    price: '$3.99',
    originalPrice: '$5.49',
    discount: '27%',
    image: 'https://images.pexels.com/photos/6287622/pexels-photo-6287622.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 2,
    available: 85,
    weight: '500g',
  },
  {
    id: '15',
    title: 'Free Range Chicken Breast',
    price: '$8.99',
    originalPrice: '$11.99',
    discount: '25%',
    image: 'https://images.pexels.com/photos/5737456/pexels-photo-5737456.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 65,
  },
  {
    id: '16',
    title: 'Organic Blueberries Fresh',
    price: '$6.99',
    originalPrice: '$8.99',
    discount: '22%',
    image: 'https://images.pexels.com/photos/2393283/pexels-photo-2393283.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 2,
    available: 45,
  },
];

export const products: Product[] = [
  {
    id: '1',
    title: 'Field Roast Chao Cheese Creamy Original',
    price: '$19.50',
    originalPrice: '$34.99',
    discount: '18%',
    image: '/placeholder.png',
    badge: 'ORGANIC',
    badgeColor: 'bg-[#00bcd4]',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 28,
  },
  {
    id: '2',
    title: 'Chobani Complete Vanilla Greek Yogurt',
    price: '$4.49',
    originalPrice: '$5.49',
    discount: '15%',
    image: '/placeholder.png',
    badge: 'RECOMMENDED',
    badgeColor: 'bg-gray-600',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 90,
    weight: '1 kg',
  },
  {
    id: '3',
    title: 'Encore Seafoods Stuffed Alaskan Salmon',
    price: '$27.49',
    originalPrice: '$33.49',
    discount: '18%',
    image: '/placeholder.png',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 97,
  },
  {
    id: '4',
    title: 'Haagen-Dazs Caramel Cone Ice Cream',
    price: '$3.48',
    originalPrice: '$6.48',
    discount: '47%',
    image: '/placeholder.png',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 20,
  },
  {
    id: '5',
    title: 'Nestle Original Coffee-Mate Coffee Creamer',
    price: '$11.99',
    originalPrice: '$13.99',
    discount: '15%',
    image: '/placeholder.png',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 49,
  },
];
