export interface Product {
  id: string;
  title: string;
  price: string;
  originalPrice: string;
  discount: string;
  image: string;
  badge?: string;
  badgeColor?: string;
  stock: string;
  rating: number;
  ratingCount: number;
  available: number;
  weight?: string;
  category?: string;
  brand?: string;
}

export interface CartItem {
  id: string;
  productId: string;
  quantity: number;
  addedAt: Date;
}

export interface WishlistItem {
  id: string;
  productId: string;
  addedAt: Date;
}

export const featuredProducts: Product[] = [
  {
    id: '1',
    title: 'USDA Choice Angus Beef Stew Meat',
    price: '$49.99',
    originalPrice: '$79.99',
    discount: '38%',
    image: 'https://images.pexels.com/photos/5632599/pexels-photo-5632599.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 28,
  },
  {
    id: '2',
    title: 'Signature Wood-Fired Mushroom and Caramelized...',
    price: '$5.99',
    originalPrice: '$7.99',
    discount: '26%',
    image: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 45,
  },
  {
    id: '3',
    title: 'Perdue Simply Smart Organics Gluten free...',
    price: '$7.99',
    originalPrice: '$8.99',
    discount: '12%',
    image: 'https://images.pexels.com/photos/3621381/pexels-photo-3621381.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 60,
  },
  {
    id: '4',
    title: 'Organic Frozen Triple Berry Blend',
    price: '$15.79',
    originalPrice: '$17.99',
    discount: '12%',
    image: 'https://images.pexels.com/photos/5737452/pexels-photo-5737452.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 52,
    weight: '500g',
  },
  {
    id: '5',
    title: 'Organic 100% Grassfed 85_15 Ground Beef',
    price: '$5.99',
    originalPrice: '$6.99',
    discount: '14%',
    image: 'https://images.pexels.com/photos/2675968/pexels-photo-2675968.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 38,
  },
];

export const bestsellerProducts: Product[] = [
  {
    id: '11',
    title: 'Premium Fresh Salmon Fillet',
    price: '$12.99',
    originalPrice: '$17.99',
    discount: '28%',
    image: 'https://images.pexels.com/photos/4148989/pexels-photo-4148989.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 2,
    available: 42,
  },
  {
    id: '12',
    title: 'Organic Valley Grass Milk',
    price: '$3.49',
    originalPrice: '$4.99',
    discount: '30%',
    image: 'https://images.pexels.com/photos/5408/food-milk-glass-bottle.jpg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 3,
    available: 120,
    weight: '1L',
  },
  {
    id: '13',
    title: 'Fresh Garden Vegetables Mix',
    price: '$4.99',
    originalPrice: '$6.99',
    discount: '29%',
    image: 'https://images.pexels.com/photos/5632598/pexels-photo-5632598.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 75,
  },
  {
    id: '14',
    title: 'Greek Yogurt Plain',
    price: '$3.99',
    originalPrice: '$5.49',
    discount: '27%',
    image: 'https://images.pexels.com/photos/6287622/pexels-photo-6287622.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 2,
    available: 85,
    weight: '500g',
  },
  {
    id: '15',
    title: 'Free Range Chicken Breast',
    price: '$8.99',
    originalPrice: '$11.99',
    discount: '25%',
    image: 'https://images.pexels.com/photos/5737456/pexels-photo-5737456.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 65,
  },
  {
    id: '16',
    title: 'Organic Blueberries Fresh',
    price: '$6.99',
    originalPrice: '$8.99',
    discount: '22%',
    image: 'https://images.pexels.com/photos/2393283/pexels-photo-2393283.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 2,
    available: 45,
  },
];

export const products: Product[] = [
  {
    id: '1',
    title: 'Field Roast Chao Cheese Creamy Original',
    price: '$19.50',
    originalPrice: '$34.99',
    discount: '18%',
    image: 'https://images.pexels.com/photos/821365/pexels-photo-821365.jpeg?auto=compress&cs=tinysrgb&w=800',
    badge: 'ORGANIC',
    badgeColor: 'bg-[#00bcd4]',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 28,
    category: 'Meats & Seafood',
    brand: 'Field Roast',
  },
  {
    id: '2',
    title: 'Chobani Complete Vanilla Greek Yogurt',
    price: '$4.49',
    originalPrice: '$5.49',
    discount: '15%',
    image: 'https://images.pexels.com/photos/6287622/pexels-photo-6287622.jpeg?auto=compress&cs=tinysrgb&w=800',
    badge: 'RECOMMENDED',
    badgeColor: 'bg-gray-600',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 90,
    weight: '1 kg',
    category: 'Breakfast & Dairy',
    brand: 'Chobani',
  },
  {
    id: '3',
    title: 'Encore Seafoods Stuffed Alaskan Salmon',
    price: '$27.49',
    originalPrice: '$33.49',
    discount: '18%',
    image: 'https://images.pexels.com/photos/4148989/pexels-photo-4148989.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 97,
    category: 'Meats & Seafood',
    brand: 'Encore Seafoods',
  },
  {
    id: '4',
    title: 'Haagen-Dazs Caramel Cone Ice Cream',
    price: '$3.48',
    originalPrice: '$6.48',
    discount: '47%',
    image: 'https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 20,
    category: 'Frozen Foods',
    brand: 'Haagen-Dazs',
  },
  {
    id: '5',
    title: 'Nestle Original Coffee-Mate Coffee Creamer',
    price: '$11.99',
    originalPrice: '$13.99',
    discount: '15%',
    image: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 49,
    category: 'Beverages',
    brand: 'Nestle',
  },
];

export const allProducts: Product[] = [
  ...featuredProducts,
  ...bestsellerProducts,
  ...products,
  {
    id: '21',
    title: 'All Natural Italian-Style Chicken Meatballs',
    price: '$7.25',
    originalPrice: '$8.99',
    discount: '20%',
    image: 'https://images.pexels.com/photos/1639562/pexels-photo-1639562.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 3,
    available: 55,
    category: 'Meats & Seafood',
    brand: 'IN STOCK',
  },
  {
    id: '22',
    title: 'Foster Farms Takeout Crispy Classic Buffalo Wings',
    price: '$7.25',
    originalPrice: '$40.98',
    discount: '30%',
    image: 'https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg?auto=compress&cs=tinysrgb&w=800',
    badge: 'RECOMMENDED',
    badgeColor: 'bg-[#e91e63]',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 2,
    available: 32,
    category: 'Meats & Seafood',
    brand: 'Foster Farms',
  },
  {
    id: '23',
    title: 'Encore Seafoods Stuffed Alaskan Salmon',
    price: '$27.48',
    originalPrice: '$35.48',
    discount: '10%',
    image: 'https://images.pexels.com/photos/3763816/pexels-photo-3763816.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 18,
    category: 'Meats & Seafood',
    brand: 'Encore',
  },
  {
    id: '24',
    title: 'Gorton\'s Beer Battered Fish Fillets',
    price: '$2.58',
    originalPrice: '$4.48',
    discount: '42%',
    image: 'https://images.pexels.com/photos/725997/pexels-photo-725997.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 44,
    category: 'Frozen Foods',
    brand: 'Gorton\'s',
  },
  {
    id: '25',
    title: 'Green Giant Veggie Spirals Zucchini',
    price: '$3.59',
    originalPrice: '$4.99',
    discount: '10%',
    image: 'https://images.pexels.com/photos/1352199/pexels-photo-1352199.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 2,
    available: 68,
    category: 'Fruits & Vegetables',
    brand: 'Green Giant',
  },
  {
    id: '26',
    title: 'Haagen-Dazs Caramel Cone Ice Cream',
    price: '$3.48',
    originalPrice: '$5.48',
    discount: '10%',
    image: 'https://images.pexels.com/photos/1352278/pexels-photo-1352278.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 1,
    available: 22,
    category: 'Frozen Foods',
    brand: 'Haagen-Dazs',
  },
  {
    id: '27',
    title: 'Organic Frozen Triple Berry Blend',
    price: '$5.99',
    originalPrice: '$8.99',
    discount: '33%',
    image: 'https://images.pexels.com/photos/5737452/pexels-photo-5737452.jpeg?auto=compress&cs=tinysrgb&w=800',
    badge: 'ORGANIC',
    badgeColor: 'bg-[#00bcd4]',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 3,
    available: 76,
    category: 'Frozen Foods',
    brand: 'Organic',
  },
  {
    id: '28',
    title: 'Perdue Simply Smart Organics Gluten Free',
    price: '$5.99',
    originalPrice: '$7.99',
    discount: '25%',
    image: 'https://images.pexels.com/photos/3621381/pexels-photo-3621381.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 40,
    category: 'Meats & Seafood',
    brand: 'Perdue',
  },
  {
    id: '29',
    title: 'Signature Wood-Fired Mushroom Pizza',
    price: '$7.25',
    originalPrice: '$9.99',
    discount: '27%',
    image: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 5,
    ratingCount: 2,
    available: 28,
    category: 'Frozen Foods',
    brand: 'Signature',
  },
  {
    id: '30',
    title: 'USDA Choice Angus Beef Stew Meat',
    price: '$5.89',
    originalPrice: '$7.99',
    discount: '26%',
    image: 'https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg?auto=compress&cs=tinysrgb&w=800',
    stock: 'IN STOCK',
    rating: 4,
    ratingCount: 1,
    available: 35,
    category: 'Meats & Seafood',
    brand: 'USDA',
  },
];
